### PR TITLE
just yea

### PR DESCRIPTION
**Pull request by ghost**
cause why not [insert shrug here]

### CODE REVIEW

**Review by DusterTheFirst — CHANGES_REQUESTED** [review]
/discord/roles.html?

**Comment by ghost** [comment]
no b because that would be a 404 page https://cdn.discordapp.com/attachments/290794868308049940/373471164435136512/unknown.png

**Comment by ghost** [comment]
it would just be roles.html

**Comment by DusterTheFirst** [comment]
i mean, you changed it to that 
screen shot 2017-10-27 at 10 15 26

**Comment by ghost** [comment]
oh whoops

**Review by DusterTheFirst — APPROVED** [review]

**Pull request merged**
